version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:clave123@db:5432/eventos
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=clave123
      - POSTGRES_DB=eventos
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: